server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_tiny?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 222222

#    cluster:
#      nodes:
#        - 192.168.6.139:6391
#        - 192.168.6.139:6392
#        - 192.168.6.139:6393
#        - 192.168.6.139:6394
#        - 192.168.6.139:6395
#        - 192.168.6.139:6396
logging:
  level:
    com:
      yangya: debug
    org:
      mybatis: debug
#mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      db-type: mysql
      id-type: auto
      #      table-prefix: t_
      table-underline: true
  mapper-locations: classpath*:/mappers/**/*.xml
  type-aliases-package: com.yangya.model

# OSS相关配置信息
aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: test # 访问身份验证中用到用户标识
    accessKeySecret: test # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: macro-oss # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://localhost:8080/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: mall/images/ # 上传文件夹路径前缀

secure:
  ignored:
    urls:
      - /
      - /swagger-ui/
      - /*.html
      - /favicon.ico
      - /**/*.html
      - /**/*.css
      - /**/*.js
      - /swagger-resources/**
      - /v2/api-docs/**
      - /actuator/**


wx:
  app-id: xxxxxxxxx
  pay:
    api-v3-key: xxxxxxxxxxxx
    certificate-serial-no: xxxxxxxxxxxxxx
    mchId: xxxxxxxxxxxxx
    notify-url: https://xxx/支付结果通知地址
    private-key-path: classpath:/certdy/apiclient_key.pem
